### PR TITLE
Added ability to override domain + documentation

### PR DESCRIPTION
**Pull request by dcousineau**
Added ability to override domain as per TODO as well as my own needs.

### CODE REVIEW

**Comment by gabegorelick** [comment]
Wow, this is getting users a lot faster than I expected :-)

This looks good (especially the documentation), but can you add some tests for this?

**Comment by dcousineau** [comment]
Certainly. [I figured it would get weird](https://twitter.com/dcousineau/status/600316795178856448) but literally this just showed up in the nick of time for my project so I'm super grateful.

**Comment by dcousineau** [comment]
Tests are up sorry about forgetting those!

**Comment by gabegorelick** [comment]
Forgot about this for a while. It's merged now. Thanks!

**Pull request merged**
